name: dotnet package

on:
  pull_request:
    types:
      - closed
    

jobs:
  build:

    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, build]
    
    steps:
      - uses: actions/checkout@v3
#      - name: Display dotnet version of CLI (different could be different from target version specified above)
#        run: dotnet --version
#      - name: Install dependencies
#        run: dotnet restore
#      - name: Build
#        run: dotnet build
#      - name: Test
#        run: dotnet test
#      - name: Publish
#        run: dotnet publish -c Release 
#      - uses: actions/upload-artifact@v3
#        with:
#          name: national-glass-build
#          path: NationalGlass/bin/Release/net6.0/publish/
      -
        name: Display credentials
        run: echo ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }} 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
          
  deploy:
    needs: build
    runs-on: [self-hosted, deploy]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download Docker image
        run: docker pull mjohnson8thlight/clockbox:latest
      - name: Start docker container
        run: docker run -d -p 5000:80 my-username/my-image:my-tag