name: dotnet package

on:
  pull_request:
    types:
      - closed
    

jobs:
  build:

    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, build]
    
    steps:
      - uses: actions/checkout@v3
#      - name: Display dotnet version of CLI (different could be different from target version specified above)
#        run: dotnet --version
#      - name: Install dependencies
#        run: dotnet restore
#      - name: Build
#        run: dotnet build
#      - name: Test
#        run: dotnet test
#      - name: Publish
#        run: dotnet publish -c Release 
#      - uses: actions/upload-artifact@v3
#        with:
#          name: national-glass-build
#          path: NationalGlass/bin/Release/net6.0/publish/
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
          
#  deploy:
#    needs: build
#    runs-on: [self-hosted, deploy]
#    steps:
#      - uses: actions/download-artifact@v3
#        with:
#            name: national-glass-build
#      - shell: powershell
#        run: Get-Process -Name dotnet -ErrorAction SilentlyContinue | Stop-Process -Force
#      - uses: actions/download-artifact@v3
#        with:
#            name: national-glass-build
#      - shell: bash
#        run: |
#          rm -rf /c/deployment
#          mkdir /c/deployment
#          cp * /c/deployment
#          cd /c/deployment
#          nohup dotnet NationalGlass.dll > /dev/null 2>&1  &
          