name: dotnet package

on:
  pull_request:
    types:
      - closed
    

jobs:
  build:

    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, build]
    
    steps:
      - uses: actions/checkout@v3
      -
        name: Display credentials
        run: echo ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }} 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nationalglass:latest
          
  deploy:
    needs: build
    runs-on: [self-hosted, deploy]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Stop and remove old container and image
        run: |
          docker stop --name national-glass
          docker container rm national-glass
          docker image rm mjohnson8thlight/nationalglass:latest
      - name: Download Docker image
        run: docker pull mjohnson8thlight/nationalglass:latest        
      - name: Start docker container
        run: docker run -d -p 5000:80 mjohnson8thlight/nationalglass:latest