name: dotnet package

on:
  pull_request:
    types:
      - closed
    

jobs:
  build:

    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, build]
    
    steps:
      - uses: actions/checkout@v3
#      - name: Setup dotnet
#        uses: actions/setup-dotnet@v3
#        id: setupstepid
#        with:
#          dotnet-version: '6.0.x'
      - name: Display dotnet version of CLI (different could be different from target version specified above)
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
      - name: Publish
        run: dotnet publish -c Release 
      - uses: actions/upload-artifact@v3
        with:
          name: national-glass-build
          path: NationalGlass/bin/Release/net6.0/publish/
    
  deploy:
    needs: build
    runs-on: [self-hosted, deploy]
    steps:
      - uses: actions/download-artifact@v3
        with:
            name: national-glass-build
      - shell: powershell
        run: Get-Process -Name dotnet -ErrorAction SilentlyContinue | Stop-Process -Force
      - shell: powershell
        run: |
          rmdir -r \deployment
          cp * \deployment
          cd \deployment
          Start-Process -FilePath "dotnet" -ArgumentList "NationalGlass.dll" 
#      - uses: actions/download-artifact@v3
#        with:
#            name: national-glass-build
#      - shell: bash
#        run:  
#          rm -r \deployment
#          cp * \deployment
#          cd \deployment
#          nohup dotnet NationalGlass.dll &
          